services:
  - type: web
    name: multiple-ml-prediction-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run mainnew.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
